### ISSUE TITLE
Crash when checking out another branch

### ISSUE THREAD

**Issue by nicolasbadia** [sproutcore/build-tools#32]
I experienced a crash when checking out another git branch. Here is the error:

    crypto.js:209
      this._binding.update(data, encoding);
                    ^
    TypeError: Not a string or buffer
        at Hash.update (crypto.js:209:17)
        at BT.ImageFile.BT.File.extend.contentHash (/.../build-tools/lib/file_types/image.js:9:38)
        at SC.Observable.get (/.../build-tools/node_modules/sproutnode/frameworks/runtime/mixins/observable.js:214:103)

**Comment by mauritslamers** [comment]
Any more information on this issue?

**Comment by nicolasbadia** [comment]
This issue as been fixed
